from PyQt5 import QtWidgets
from GUI.Autogenerated.SettingsWindow.AGDayCalendarSet import Ui_Form


class DayCalendarSet(QtWidgets.QWidget):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.dayCalendarSet = Ui_Form()
        self.dayCalendarSet.setupUi(self)
        self.init_ui()

    def init_ui(self) -> None:
        pass


def __main__():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dayCalendarSet = DayCalendarSet()
    dayCalendarSet.show()
    sys.exit(app.exec_())

if __name__ == '__main__':
    __main__()
