from PyQt5 import QtWidgets
from GUI.Autogenerated.SettingsWindow.AGDayCalendarSet import Ui_Form
from Objects.AppSettings import DayCalendarSettings
from GUI.MainWindow.ColorSettingWindow import *


class DayCalendarSet(QtWidgets.QWidget):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.dayCalendarSet = Ui_Form()
        self.dayCalendarSet.setupUi(self)
        self.dialogColorW = Window()
        self.init_ui()

    def init_ui(self) -> None:
        pass

    def getColorFromDialog(self):
        self.color_RGB = self.dialogColorW.ReturnColor().name()

    def setCurrentData(self, settingsDict):
        self.dayCalendarSet.calendarBackColourBtn.setStyleSheet(f"background-color:{settingsDict['calendarBackColour']}")
        self.dayCalendarSet.linesColourBtn.setStyleSheet(f"background-color:{settingsDict['linesColour']}")
        self.dayCalendarSet.hourLinesThicknessRatioSpinBox.setValue(settingsDict['hourLinesThicknessRatio'])
        self.dayCalendarSet.eventSpaceRatioSpinBox.setValue(settingsDict['spaceRatioBetweenEvents'])
        self.dayCalendarSet.titleCheckBox.setChecked(bool(settingsDict['eventTitleShow']))
        self.dayCalendarSet.descriptionCheckBox.setChecked(bool(settingsDict['eventDescriptionShow']))
        self.dayCalendarSet.localizationCheckBox.setChecked(bool(settingsDict['eventLocalizationShow']))
        self.dayCalendarSet.reminderCheckBox.setChecked(bool(settingsDict['eventReminderShow']))

    def getCurrentData(self):
        return DayCalendarSettings(
            self.dayCalendarSet.calendarBackColourBtn.palette().window().color().name(),
            self.dayCalendarSet.linesColourBtn.palette().window().color().name(),
            self.dayCalendarSet.hourLinesThicknessRatioSpinBox.value(),
            self.dayCalendarSet.eventSpaceRatioSpinBox.value(),
            self.dayCalendarSet.titleCheckBox.isChecked(),
            self.dayCalendarSet.descriptionCheckBox.isChecked(),
            self.dayCalendarSet.localizationCheckBox.isChecked(),
            self.dayCalendarSet.reminderCheckBox.isChecked()
        )


def __main__():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dayCalendarSet = DayCalendarSet()
    dayCalendarSet.show()
    sys.exit(app.exec_())

if __name__ == '__main__':
    __main__()
