from PyQt5 import QtWidgets
from GUI.Autogenerated.SettingsWindow.AGEventTypesSet import Ui_Form


class EventTypesSet(QtWidgets.QWidget):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.eventTypesSet = Ui_Form()
        self.eventTypesSet.setupUi(self)
        self.init_ui()

        self.eventTypesSet.addTypeBtn.setStyleSheet("QPushButton {"

                                                     "border-radius: 6px;"
                                                     "  background-image: url(./WindowObjects/Resources/addImage_24.png);"
                                                     "background-repeat:no-repeat;"
                                                     " background-position:center;"
                                                     "  min-width: 30px;"
                                                     "}"

                                                     "QPushButton:pressed {"
                                                     "   background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,"
                                                     " stop: 0 #dadbde, stop: 1 #f6f7fa);"
                                                     "}"

                                                     "QPushButton:flat {"
                                                     "   border: none; /* no border for a flat push button */"
                                                     "}"

                                                     "QPushButton:default {"
                                                     "    border-color: navy; /* make the default button prominent */"
                                                     "}")
        self.eventTypesSet.removeTypeBtn.setStyleSheet("QPushButton {"

                                                          "border-radius: 6px;"
                                                          "  background-image: url(./WindowObjects/Resources/trashImage_24.png);"
                                                          "background-repeat:no-repeat;"
                                                          " background-position:center;"
                                                          "  min-width: 40px;"
                                                          "}"

                                                          "QPushButton:pressed {"
                                                          "   background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,"
                                                          " stop: 0 #dadbde, stop: 1 #f6f7fa);"
                                                          "}"

                                                          "QPushButton:flat {"
                                                          "   border: none; /* no border for a flat push button */"
                                                          "}"

                                                          "QPushButton:default {"
                                                          "    border-color: navy; /* make the default button prominent */"
                                                          "}")
        self.eventTypesSet.editTypeBtn.setStyleSheet("QPushButton {"

                                                     "border-radius: 6px;"
                                                     "  background-image: url(./WindowObjects/Resources/editImage_24.png);"
                                                     "background-repeat:no-repeat;"
                                                     " background-position:center;"
                                                     "  min-width: 40px;"
                                                     "}"

                                                     "QPushButton:pressed {"
                                                     "   background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,"
                                                     " stop: 0 #dadbde, stop: 1 #f6f7fa);"
                                                     "}"

                                                     "QPushButton:flat {"
                                                     "   border: none; /* no border for a flat push button */"
                                                     "}"

                                                     "QPushButton:default {"
                                                     "    border-color: navy; /* make the default button prominent */"
                                                     "}")

    def init_ui(self) -> None:
        pass


def __main__():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    eventTypesSet = EventTypesSet()
    eventTypesSet.show()
    sys.exit(app.exec_())


if __name__ == '__main__':
    __main__()