from PyQt5 import QtWidgets
from GUI.Autogenerated.SettingsWindow.AGMonthCalendarSet import Ui_Form


class MonthCalendarSet(QtWidgets.QWidget):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.monthCalendarSet = Ui_Form()
        self.monthCalendarSet.setupUi(self)
        self.init_ui()

    def init_ui(self) -> None:
        pass


def __main__():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    monthCalendarSet = MonthCalendarSet()
    monthCalendarSet.show()
    sys.exit(app.exec_())


if __name__ == '__main__':
    __main__()