from PyQt5 import QtWidgets
from GUI.Autogenerated.SettingsWindow.AGMonthCalendarSet import Ui_Form
from Objects.AppSettings import MonthCalendarSettings


class MonthCalendarSet(QtWidgets.QWidget):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.monthCalendarSet = Ui_Form()
        self.monthCalendarSet.setupUi(self)
        self.init_ui()

    def init_ui(self) -> None:
        pass

    def setCurrentData(self, settingsDict):
        self.monthCalendarSet.weekNumberColourBtn.setStyleSheet(f"background-color:{settingsDict['weekNumbersColour']}")
        self.monthCalendarSet.weekDaysColourBtn.setStyleSheet(f"background-color:{settingsDict['weekDaysColour']}")
        self.monthCalendarSet.currentDayColourBtn.setStyleSheet(f"background-color:{settingsDict['currentDayColour']}")
        self.monthCalendarSet.selectedDayColourBtn.setStyleSheet(
            f"background-color:{settingsDict['selectedDayColour']}")
        self.monthCalendarSet.prevMonthColourBtn.setStyleSheet(f"background-color:{settingsDict['prevMonthColour']}")
        self.monthCalendarSet.currentMonthColourBtn.setStyleSheet(
            f"background-color:{settingsDict['currentMonthColour']}")
        self.monthCalendarSet.nextMonthColourBtn.setStyleSheet(f"background-color:{settingsDict['nextMonthColour']}")

        self.monthCalendarSet.weekNumberFontRatioSpinBox.setValue(settingsDict['weekNumbersFontRatio'])
        self.monthCalendarSet.weekDaysFontRatioSpinBox.setValue(settingsDict['weekDaysFontRatio'])
        self.monthCalendarSet.currentDayFontRatioSpinBox.setValue(settingsDict['currentDayFontRatio'])
        self.monthCalendarSet.selectedDayFontRatioSpinBox.setValue(settingsDict['selectedDayFontRatio'])
        self.monthCalendarSet.prevMonthFontRatioSpinBox.setValue(settingsDict['prevMonthFontRatio'])
        self.monthCalendarSet.currentMonthFontRatioSpinBox.setValue(settingsDict['currentMonthFontRatio'])
        self.monthCalendarSet.nextMonthFontRatioSpinBox.setValue(settingsDict['nextMonthFontRatio'])

        self.monthCalendarSet.currentDayBoldCheckBox.setChecked(bool(settingsDict['todayDateBold']))

    def getCurrentData(self):
        return MonthCalendarSettings(self.monthCalendarSet.weekNumberColourBtn.palette().window().color().name(),
                                     self.monthCalendarSet.weekDaysColourBtn.palette().window().color().name(),
                                     self.monthCalendarSet.currentDayColourBtn.palette().window().color().name(),
                                     self.monthCalendarSet.selectedDayColourBtn.palette().window().color().name(),
                                     self.monthCalendarSet.prevMonthColourBtn.palette().window().color().name(),
                                     self.monthCalendarSet.currentMonthColourBtn.palette().window().color().name(),
                                     self.monthCalendarSet.nextMonthColourBtn.palette().window().color().name(),

                                     self.monthCalendarSet.weekNumberFontRatioSpinBox.value(),
                                     self.monthCalendarSet.weekDaysFontRatioSpinBox.value(),
                                     self.monthCalendarSet.currentDayFontRatioSpinBox.value(),
                                     self.monthCalendarSet.selectedDayFontRatioSpinBox.value(),
                                     self.monthCalendarSet.prevMonthFontRatioSpinBox.value(),
                                     self.monthCalendarSet.currentMonthFontRatioSpinBox.value(),
                                     self.monthCalendarSet.nextMonthFontRatioSpinBox.value(),

                                     self.monthCalendarSet.currentDayBoldCheckBox.isChecked()
                                     )

def __main__():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    monthCalendarSet = MonthCalendarSet()
    monthCalendarSet.show()
    sys.exit(app.exec_())


if __name__ == '__main__':
    __main__()
