from PyQt5 import QtWidgets
from GUI.Autogenerated.SettingsWindow.AGWeekCalendarSet import Ui_Form


class WeekCalendarSet(QtWidgets.QWidget):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.weekCalendarSet = Ui_Form()
        self.weekCalendarSet.setupUi(self)
        self.init_ui()

    def init_ui(self) -> None:
        pass


def __main__():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    weekCalendarSet = WeekCalendarSet()
    weekCalendarSet.show()
    sys.exit(app.exec_())


if __name__ == '__main__':
    __main__()