from PyQt5 import QtWidgets
from GUI.Autogenerated.SettingsWindow.AGWeekCalendarSet import Ui_Form
from Objects.AppSettings import WeekCalendarSettings
from GUI.MainWindow.ColorSettingWindow import *


class WeekCalendarSet(QtWidgets.QWidget):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.weekCalendarSet = Ui_Form()
        self.weekCalendarSet.setupUi(self)
        self.dialogColorW = Window()
        self.init_ui()

    def init_ui(self) -> None:
        pass

    def getColorFromDialog(self):
        self.color_RGB = self.dialogColorW.ReturnColor().name()

    def setCurrentData(self, settingsDict):
        self.weekCalendarSet.calendarBackColourBtn.setStyleSheet(f"background-color:{settingsDict['calendarBackColour']}")
        self.weekCalendarSet.hourLinesColourBtn.setStyleSheet(f"background-color:{settingsDict['hourLinesColour']}")
        self.weekCalendarSet.dayLinesColourBtn.setStyleSheet(f"background-color:{settingsDict['dayLinesColour']}")
        self.weekCalendarSet.hourLinesRatioSpinBox.setValue(settingsDict['hourLinesThicknessRatio'])
        self.weekCalendarSet.weekLinesRatioSpinBox.setValue(settingsDict['dayLinesThicknessRatio'])

    def getCurrentData(self):
        return WeekCalendarSettings(self.weekCalendarSet.calendarBackColourBtn.palette().window().color().name(),
                                    self.weekCalendarSet.hourLinesColourBtn.palette().window().color().name(),
                                    self.weekCalendarSet.dayLinesColourBtn.palette().window().color().name(),
                                    self.weekCalendarSet.hourLinesRatioSpinBox.value(),
                                    self.weekCalendarSet.weekLinesRatioSpinBox.value()
                                    )

def __main__():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    weekCalendarSet = WeekCalendarSet()
    weekCalendarSet.show()
    sys.exit(app.exec_())


if __name__ == '__main__':
    __main__()
