# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AGNewEventTypeW.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from GUI.ColorSettingWindow import *

class Ui_NewEventTypeWindow(object):
    def setupUi(self, NewEventTypeWindow):
        NewEventTypeWindow.setObjectName("NewEventTypeWindow")
        NewEventTypeWindow.setEnabled(True)
        NewEventTypeWindow.resize(450, 250)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NewEventTypeWindow.sizePolicy().hasHeightForWidth())
        NewEventTypeWindow.setSizePolicy(sizePolicy)
        NewEventTypeWindow.setStyleSheet("background-color: rgb(204, 229, 255);")
        self.centralwidget = QtWidgets.QWidget(NewEventTypeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(80, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(300, 0))
        self.plainTextEdit.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout.addWidget(self.plainTextEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.setEventColorButton = QtWidgets.QPushButton(self.centralwidget)
        self.setEventColorButton.setMinimumSize(QtCore.QSize(200, 0))
        self.setEventColorButton.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.setEventColorButton.setFont(font)
        self.setEventColorButton.setStyleSheet("background-color: rgb(166, 166, 166);")
        self.setEventColorButton.setObjectName("setEventColorButton")
        self.setEventColorButton.clicked.connect(self.getColorFromDialog)
        self.horizontalLayout_2.addWidget(self.setEventColorButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem6, 1, 0, 1, 1)
        NewEventTypeWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(NewEventTypeWindow)
        QtCore.QMetaObject.connectSlotsByName(NewEventTypeWindow)
        self.dialog = Window()

    def retranslateUi(self, NewEventTypeWindow):
        _translate = QtCore.QCoreApplication.translate
        NewEventTypeWindow.setWindowTitle(_translate("NewEventTypeWindow", "New Event Type"))
        self.label.setText(_translate("NewEventTypeWindow", "Name:"))
        self.setEventColorButton.setText(_translate("NewEventTypeWindow", "Set event color"))

    def getColorFromDialog(self):
        self.color_RGB = self.dialog.ReturnColor()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewEventTypeWindow = QtWidgets.QMainWindow()
    ui = Ui_NewEventTypeWindow()
    ui.setupUi(NewEventTypeWindow)
    NewEventTypeWindow.show()
    sys.exit(app.exec_())
