from PyQt5.QtWidgets import QSizePolicy

from GUI.Autogenerated.AGMainW import Ui_MainWindow
import GUI.NewEventW as newEventW
from PyQt5 import QtCore, QtGui, QtWidgets

from GUI.DayCalendarWidget import DayCalendarWidget
from Objects.Event import loadEventsList, loadEventTypesList
from GUI.MainCalendarWidget import MainCalendarWidget


class MainWindow(QtWidgets.QMainWindow):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        loadEventsList()
        loadEventTypesList()
        self.mainCalendarWidget = MainCalendarWidget()
        self.dayCalendarWidget = DayCalendarWidget()
        self.ui.stackedWidget.addWidget(self.mainCalendarWidget)
        self.ui.stackedWidget.addWidget(self.dayCalendarWidget)
        self.ui_newEventWindow = newEventW.NewEventW()
        self.ui.newEventButton.clicked.connect(self.openNewEventWindow)
        self.ui.prevButton.clicked.connect(self.setDateInBarToPrev)
        self.ui.nextButton.clicked.connect(self.setDateInBarToNext)
        self.setDateInBar()
        self.mainCalendarWidget.clickedDaySignal.connect(self.setClickedDateInBar)
        self.ui_newEventWindow.newEventAddedSignal.connect(self.mainCalendarWidget.updateEventTypeColours)

        self.ui.dayCalendarButton.clicked.connect(self.switchToTheDayCalendar)
        self.ui.monthCalendarButton.clicked.connect(self.switchToTheMonthCalendar)

        self.setMinimumSize(1300, 600)

    def resizeEvent(self, a0: QtGui.QResizeEvent) -> None:
        self.mainCalendarWidget.updateWidgetSize()

    def setDateInBar(self):
        self.ui.dayFromDate.setText(str(self.mainCalendarWidget.dateOnDateBar.day))
        self.ui.monthFromDate.setText(self.mainCalendarWidget.dateOnDateBar.strftime("%B"))
        self.ui.yearFromDate.setText(str(self.mainCalendarWidget.dateOnDateBar.year))

    @QtCore.pyqtSlot()
    def setClickedDateInBar(self):
        self.setDateInBar()

    def getDateOnDateBar(self):
        return self.dateOnDateBar

    def setDateInBarToPrev(self):
        if self.ui.stackedWidget.currentIndex() == 0:
            self.mainCalendarWidget.changeDate("month", "prev")
        elif self.ui.stackedWidget.currentIndex() == 1:
            self.mainCalendarWidget.changeDate("day", "prev")

        self.setDateInBar()

    def setDateInBarToNext(self):
        if self.ui.stackedWidget.currentIndex() == 0:
            self.mainCalendarWidget.changeDate("month", "next")
        elif self.ui.stackedWidget.currentIndex() == 1:
            self.mainCalendarWidget.changeDate("day", "next")

        self.setDateInBar()

    def openNewEventWindow(self):
        self.ui_newEventWindow.setDateFromCalendar(self.mainCalendarWidget.dateOnDateBar)
        self.ui_newEventWindow.timeEditDisabled()
        self.ui_newEventWindow.clearEventDataInFormular()
        self.ui_newEventWindow.show()

    def switchToTheDayCalendar(self):
        self.ui.stackedWidget.setCurrentIndex(1)

    def switchToTheMonthCalendar(self):
        self.ui.stackedWidget.setCurrentIndex(0)
