from GUI.Autogenerated.AGMainW import Ui_MainWindow
import GUI.NewEventW as newEventW
from PyQt5 import QtCore, QtGui, QtWidgets
from Objects.Event import loadEventsList, loadEventTypesList
from GUI.MainCalendarWidget import MainCalendarWidget


class MainWindow(QtWidgets.QMainWindow):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        loadEventsList()
        loadEventTypesList()
        self.mainCalendarWidget = MainCalendarWidget()
        self.ui.stackedWidget.addWidget(self.mainCalendarWidget)
        self.ui_newEventWindow = newEventW.NewEventW()
        self.ui.newEventButton.clicked.connect(self.openNewEventWindow)
        self.ui.prevButton.clicked.connect(self.setDateInBarToPrevMonth)
        self.ui.nextButton.clicked.connect(self.setDateInBarToNextMonth)
        self.setDateInBar()
        self.mainCalendarWidget.clickedDaySignal.connect(self.setClickedDateInBar)
        self.ui_newEventWindow.newEventAddedSignal.connect(self.mainCalendarWidget.updateEventTypeColours)

    def resizeEvent(self, a0: QtGui.QResizeEvent) -> None:
        self.mainCalendarWidget.updateWidgetSize()

    def setDateInBar(self):
        self.ui.dayFromDate.setText(str(self.mainCalendarWidget.dateOnDateBar.day))
        self.ui.monthFromDate.setText(self.mainCalendarWidget.dateOnDateBar.strftime("%B"))
        self.ui.yearFromDate.setText(str(self.mainCalendarWidget.dateOnDateBar.year))

    @QtCore.pyqtSlot()
    def setClickedDateInBar(self):
        self.setDateInBar()

    def getDateOnDateBar(self):
        return self.dateOnDateBar

    def setDateInBarToPrevMonth(self):
        self.mainCalendarWidget.changeMonthToPrev()
        self.setDateInBar()

    def setDateInBarToNextMonth(self):
        self.mainCalendarWidget.changeMonthToNext()
        self.setDateInBar()

    def openNewEventWindow(self):
        self.ui_newEventWindow.setDateFromCalendar(self.mainCalendarWidget.dateOnDateBar)
        self.ui_newEventWindow.timeEditDisabled()
        self.ui_newEventWindow.clearEventDataInFormular()
        self.ui_newEventWindow.show()