from PyQt5 import QtCore, QtWidgets
from GUI.Autogenerated.AGSettingsW import Ui_Form


class SettingsW(QtWidgets.QWidget):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.settingsWindow = Ui_Form()
        self.settingsWindow.setupUi(self)
        self.init_ui()

    def init_ui(self) -> None:
        self.settingsWindow.listWidget.insertItem(0, 'General')
        self.settingsWindow.listWidget.insertItem(1, 'Day calendar')
        self.settingsWindow.listWidget.insertItem(2, 'Week calendar')
        self.settingsWindow.listWidget.insertItem(3, 'Month calendar')

    #TODO day: tło na siatce, kolor i grubosc linii, przerwy miedzy prostokatami, dodatkowe informacje


def __main__():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    settingsW = SettingsW()
    settingsW.show()
    sys.exit(app.exec_())

if __name__ == '__main__':
    __main__()