from PyQt5 import QtWidgets
from GUI.Autogenerated.AGWeekCalendarWidget import Ui_Form


class WeekCalendarWidget(QtWidgets.QWidget):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.weekCalendarWidget = Ui_Form()
        self.weekCalendarWidget.setupUi(self)

