from PyQt5 import QtWidgets
from GUI.Autogenerated.MainWindow.AGEventDataW import Ui_Form
from Objects.Event import Event
from WindowObjects.DayCalendar import DayCalendar
from Objects.Event import getEventTypeColour
from datetime import datetime
from PyQt5 import QtWidgets, QtCore


class EventDataW(QtWidgets.QWidget):
    eventEditSignal = QtCore.pyqtSignal()

    #self.eventDict: Event

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.eventDataWidget = Ui_Form()
        self.eventDataWidget.setupUi(self)
        self.eventDataWidget.eventEditBtn.setStyleSheet("QPushButton {"

                                                             "border-radius: 6px;"
                                                             "  background-image: url(./WindowObjects/editImage.png);"
                                                             "background-repeat:no-repeat;"
                                                             " background-position:center;"
                                                             "  min-width: 40px;"
                                                             "}"

                                                             "QPushButton:pressed {"
                                                             "   background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,"
                                                             " stop: 0 #dadbde, stop: 1 #f6f7fa);"
                                                             "}"

                                                             "QPushButton:flat {"
                                                             "   border: none; /* no border for a flat push button */"
                                                             "}"

                                                             "QPushButton:default {"
                                                             "    border-color: navy; /* make the default button prominent */"
                                                             "}")
        self.eventDataWidget.eventRemoveBtn.setStyleSheet("QPushButton {"

                                                        "border-radius: 6px;"
                                                        "  background-image: url(./WindowObjects/trashImage.png);"
                                                        "background-repeat:no-repeat;"
                                                        " background-position:center;"
                                                        "  min-width: 40px;"
                                                        "}"

                                                        "QPushButton:pressed {"
                                                        "   background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,"
                                                        " stop: 0 #dadbde, stop: 1 #f6f7fa);"
                                                        "}"

                                                        "QPushButton:flat {"
                                                        "   border: none; /* no border for a flat push button */"
                                                        "}"

                                                        "QPushButton:default {"
                                                        "    border-color: navy; /* make the default button prominent */"
                                                        "}")
        self.eventDataWidget.eventEditBtn.clicked.connect(self.eventEditBtnPress)

    def setLabelsText(self, eventDict: Event):
        # self.eventDict = eventDict
        self.eventDataWidget.eventDateLabel.setText(eventDict.eventDuration.timeFrom.strftime('%d - %m - %Y'))
        self.eventDataWidget.timeFromLabel.setText(eventDict.eventDuration.timeFrom.strftime('%H:%M'))
        self.eventDataWidget.timeToLabel.setText(eventDict.eventDuration.timeTo.strftime('%H:%M'))
        self.eventDataWidget.titleLabel.setText(eventDict.title)
        self.eventDataWidget.eventTypeLabel.setText(eventDict.type)
        self.eventDataWidget.eventDescriptionLabel.setText(eventDict.description)
        self.eventDataWidget.eventLocalizationLabel.setText(eventDict.localization)
        self.eventDataWidget.eventReminderLabel.setText(eventDict.reminder)

    def eventEditBtnPress(self):
        pass
        # self.eventEditSignal.emit(self.eventDict)