from PyQt5 import QtWidgets
from GUI.Autogenerated.MainWindow.AGWeekCalendarWidget import Ui_Form
from WindowObjects.WeekCalendar import WeekCalendar


class WeekCalendarWidget(QtWidgets.QWidget):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.weekCalendarWidget = Ui_Form()
        self.weekCalendarWidget.setupUi(self)
        self.weekCalendar = WeekCalendar()
        self.weekCalendarWidget.scrollArea.setWidget(self.weekCalendar)

